{
  "hash": "60691213f2ab17e8069b4d06395ac737",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"US Names: section 2.3 of Regression and Other Stories\"\ndate: \"2024-09-02\"\ncategories: [ROS]\n---\n\nIn section 2.3 of Regression and Other Stories, Gelman et al. discuss using graphs to learn more about data. The third example involves the exploration of names in the United States from 1880 to 2010. In this post I recreate figures 2.6 - 2.9 using R code that makes more sense to me. The original data and code are in [this GitHub repo](https://github.com/avehtari/ROS-Examples/tree/master/Names).\n\nFirst read in the data and drop the superfluous first column which just contains row numbers:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nallnames <- read.csv(\"https://github.com/avehtari/ROS-Examples/raw/master/Names/data/allnames_clean.csv\")\nallnames$X <- NULL\ndim(allnames)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 98012   133\n```\n\n\n:::\n:::\n\n\nNotice this data set is quite large and \"wide\" with over 98,000 rows and 133 columns. There is one row per name per sex with counts per year spanning from 1880 to 2010. Here's a portion of the data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nallnames[1:3,1:6]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  name sex X1880 X1881 X1882 X1883\n1 Mary   F  7065  6919  8149  8012\n2 Anna   F  2604  2698  3143  3306\n3 Emma   F  2003  2034  2303  2367\n```\n\n\n:::\n:::\n\n\nApparently 7,065 girls were named Mary in 1880, and then 6,919 in 1881, and so on.\n\nFigs 2.6 and 2.7 show the distribution of the last letters of boys' first names for the years 1906, 1956, and 2006. I wrote a function to create the plots for a given year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlast_letter <- function(year){\n  xyear <- paste0(\"X\", year)\n  d <- subset(allnames, sex == \"M\", select = c(\"name\", xyear))\n  n <- nchar(d$name)\n  d$last <- substr(d$name, n, n)\n  d$last <- factor(d$last, levels = letters, labels = letters)\n  p_data <- aggregate(d[[xyear]], by = list(d[[\"last\"]]), sum)\n  names(p_data) <- c(\"letter\", \"count\")\n  p_data$p <- p_data[[\"count\"]]/sum(p_data[[\"count\"]])\n  barplot(p ~ letter, data = p_data, \n          main = paste(\"Last letter of boys' names in\", year))\n}\n```\n:::\n\n\nNow create the plots:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlast_letter(1906)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=960}\n:::\n\n```{.r .cell-code}\nlast_letter(1956)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-2.png){width=960}\n:::\n\n```{.r .cell-code}\nlast_letter(2006)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-3.png){width=960}\n:::\n:::\n\n\nThe 2006 plot shows a trend in giving boys names that end with the letter \"n\", such as Ethan, Jayden, Aiden, Mason, and Logan.\n\nFig 2.8 looks at the distribution of the letters of boys' last names over time. To create this plot I found it helpful to use the {tidyr} and {dplyr} packages. First I reshaped the data to \"long\" format using `pivot_longer()` so there is one row per name per sex per year. Then I removed the \"X\" from the year value and once again extracted the last letter of the last names using the `nchar()` and `substr()` functions.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyr)\nallnames_long <- pivot_longer(allnames, cols = X1880:X2010, \n                              names_to = \"year\", values_to = \"count\")\nallnames_long$year <- sub(\"X\", \"\", allnames_long$year)\nn <- nchar(allnames_long$name)\nallnames_long$last <- substr(allnames_long$name, n, n)\nallnames_long$last <- factor(allnames_long$last, \n                             levels = letters, labels = letters)\n```\n:::\n\n\nNext I used some {dplyr} functions to calculate the proportions of boys' names ending in one of the 26 English letters by year. In the last step I create a new variable called \"last2\" to indicate if the letter was an N, D or Y. This is to help create a plot matching figure 2.8\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlast_letter_males <- allnames_long |> \n  filter(sex == \"M\") |> \n  group_by(year, last) |> \n  summarise(letter_count = sum(count)) |> \n  mutate(p = letter_count/sum(letter_count),\n         last2 = case_when(last == \"n\" ~ \"n\",\n                           last == \"d\" ~ \"d\",\n                           last == \"y\" ~ \"y\",\n                           .default = \"other\"))\n```\n:::\n\n\nBefore I create the plot, I cut the data into two sets: one with letters N, D and Y; and one with the rest of the letters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nndy <- subset(last_letter_males, last2 != \"other\")\nother <- subset(last_letter_males, last2 == \"other\")\n```\n:::\n\n\nAnd now to create the plot using {ggplot2}. Using two data sets allows me to tweak the lines for the letters N, D and Y The \"Set2\" palette is a good all-purpose color blind friendly palette.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot() +\n  aes(x = year, y = p, group = last) +\n  geom_line(data = other, alpha = 1/5) +\n  geom_line(mapping = aes(color = last2), data = ndy, linewidth = 1.5) +\n  scale_x_discrete(breaks = c(\"1900\", \"1950\", \"2000\")) +\n  scale_color_brewer(palette = \"Set2\") +\n  theme_minimal() +\n  labs(color = \"letter\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\nNames ending in D and Y had their moments in the sun, but now it's all about names ending in N.\n\nFigure 2.9 displays trends in the concentrations of names in the top 10. This was the easiest plot to create. Again I used some {dplyr} reasoning to create the data. After I calculate proportions of counts by year and sex, I sort the data in descending order, slice off the top 10 names, and then sum the proportions by year and sex.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnames_conc <- allnames_long |>\n  group_by(year, sex) |> \n  mutate(p = count/sum(count)) |> \n  arrange(desc(p)) |> \n  slice_head(n = 10) |> \n  summarize(total_p = sum(p))\n```\n:::\n\n\nAnd here's the plot:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(names_conc) + \n  aes(x = year, y = total_p, group = sex, color = sex) +\n  geom_line() +\n  scale_x_discrete(breaks = c(\"1900\", \"1950\", \"2000\")) +\n  scale_color_brewer(palette = \"Set2\") +\n  ylim(c(0, 0.45)) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n:::\n\n\nPre 1900, about 40% of all boys' names were in the top 10. Fast forward 100 years to 2000, only about 10% of names, boy or girl, are in the top 10. We see much more variability in names in the 21st century. \n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}