{
  "hash": "d18b9b2f51a3a63d60048b2c673f34a1",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Predicted means for a PO model\"\ndate: \"2025-11-25\"\ncategories: [rms, PO model]\n---\n\n\nI was reading [section 7.6](https://hbiostat.org/bbr/nonpar#generalization-of-the-wilcoxonkruskal-wallis-test) of Harrell's BBR and came across this example that shows how a proportional odds (PO) model can be used in place of a Kruskal-Wallis test.\n\nHere's the code presented to generate some data:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\ngroup <- rep(c('A','B','C','D'), 100)\ny <- rnorm(400, 100, 15) + 10*(group == 'B') + 20*(group=='C') + 30*(group=='D')\n```\n:::\n\n\nNotice these are four samples from normal distributions with the same variances but different means. No special test is needed. But Harrell uses this data to demonstrate how well the PO model performs even when it isn't needed.\n\nHere's the analysis using the `orm()` function from the rms package.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(rms)\ndd <- datadist(group, y); options(datadist='dd')\nf <- orm(y ~ group)\nf    # use LR chi-square test as replacement for Kruskal-Wallis\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nLogistic (Proportional Odds) Ordinal Regression Model\n\norm(formula = y ~ group)\n\n                          Model Likelihood               Discrimination    Rank Discrim.    \n                                Ratio Test                      Indexes          Indexes    \nObs              400    LR chi2     193.31    R2                  0.383    rho     0.633    \nESS              400    d.f.             3    R2(3,400)           0.379    Dxy     0.426    \nDistinct Y       400    Pr(> chi2) <0.0001    R2(3,400)           0.379                     \nMedian Y    115.4143    Score chi2  193.21    |Pr(Y>=median)-0.5| 0.256                     \nmax |deriv|    2e-11    Pr(> chi2) <0.0001                                                  \n\n        Coef   S.E.   Wald Z Pr(>|Z|)\ngroup=B 1.4221 0.2579  5.51  <0.0001 \ngroup=C 2.6624 0.2762  9.64  <0.0001 \ngroup=D 3.6606 0.2925 12.52  <0.0001 \n```\n\n\n:::\n:::\n\n\nThere's a lot of output, but the LR chi-square test is the replacement for Kruskal-Wallis. LR chi2 = 193.31, p < 0.0001.\n\nNow here comes the part that was new to me. The PO model can be used to estimate _means_ from the model. Here's how it's done with rms.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nM <- Mean(f)\nPredict(f, group, fun=M)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  group      yhat     lower    upper\n1     A  99.32328  96.46657 102.1800\n2     B 111.21326 108.27169 114.1548\n3     C 121.63880 118.78670 124.4909\n4     D 129.70290 127.07203 132.3338\n\nResponse variable (y):  \n\nLimits are 0.95 confidence limits\n```\n\n\n:::\n:::\n\n\nThese compare favorably to the sample means.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummarize(y, group, smean.cl.normal)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  group         y     Lower    Upper\n1     A  98.72953  95.81508 101.6440\n2     B 111.69464 108.61130 114.7780\n3     C 121.80841 118.93036 124.6865\n4     D 130.05275 127.40318 132.7023\n```\n\n\n:::\n:::\n\n\nI thought a PO model returned probabilities. How does this work? Harrell explains it in a footnote:\n\n> The predicted mean for a set of covariate settings is obtained by using all the intercepts and betas to get exceedance probabilities for Y >= y, taking successive differences in those probabilities to get cell probabilities that Y = y, then multiplying cell probabilities by the value attached to them, and summing. This is the formula for the mean for a discrete distribution.\n\nThis blog post shows how to implement this.\n\nThe first thing we need to do is get the linear predictors. These are just the three model coefficients. We also need to append 0 to account for the reference level. But notice the indexing. There are 399 intercepts! That's right, the `orm()` function works with continuous responses. Since we have 400 unique observations, we have 399 intercepts. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlp <- c(0, coef(f)[400:402])\nlp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          group=B  group=C  group=D \n0.000000 1.422081 2.662447 3.660646 \n```\n\n\n:::\n:::\n\n\nNext we get the intercepts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercepts <- coef(f)[1:399]\nhead(intercepts)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ny>=63.9535568 y>=65.6631403  y>=65.721467 y>=66.0266597 y>=71.2846086 \n     4.887868      4.187155      3.774066      3.478702      3.247817 \ny>=71.4256683 \n     3.057693 \n```\n\n\n:::\n:::\n\n\nNow add intercepts to all linear predictors. This creates a 4 x 399 matrix with one column per intercept. Each column contains log odds of each group exceeding the given intercept value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nxb <- sapply(intercepts, \"+\", lp)\nxb[,1:4]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        y>=63.9535568 y>=65.6631403 y>=65.721467 y>=66.0266597\n             4.887868      4.187155     3.774066      3.478702\ngroup=B      6.309950      5.609236     5.196147      4.900783\ngroup=C      7.550316      6.849603     6.436514      6.141149\ngroup=D      8.548514      7.847801     7.434712      7.139347\n```\n\n\n:::\n:::\n\n\nAfter that, we convert to _exceedance probabilities_ ($Y \\ge y$) using the inverse logit. We see in the first column that each group has very high probability of exceeding 63.9535568.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nP <- matrix(plogis(xb), ncol = 399)\ncolnames(P) <- names(intercepts)\nP[,1:4]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     y>=63.9535568 y>=65.6631403 y>=65.721467 y>=66.0266597\n[1,]     0.9925189     0.9850378    0.9775567     0.9700757\n[2,]     0.9981852     0.9963495    0.9944926     0.9926142\n[3,]     0.9994743     0.9989412    0.9984006     0.9978522\n[4,]     0.9998062     0.9996095    0.9994099     0.9992074\n```\n\n\n:::\n:::\n\n\nTo get _cell probabilities_ ($Y = y$) we need to take successive differences in exceedance probabilities. We can do this with simple subtraction. Adding a column of 1s adds the probability ceiling of 1. Adding a column of 0s adds the probability floor of 0. The first column shows group probabilities for y = 61.11508, the \"baseline\" y value. The second column shows the group probabilities for y = 63.95356. And so on.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nP <- cbind(1, P) - cbind(P, 0)\nP[,1:4]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                  y>=63.9535568 y>=65.6631403 y>=65.721467\n[1,] 0.0074810843  0.0074810843  0.0074810843 0.0074810843\n[2,] 0.0018148255  0.0018356660  0.0018568676 0.0018784386\n[3,] 0.0005256675  0.0005330871  0.0005406649 0.0005484054\n[4,] 0.0001937954  0.0001966622  0.0001995931 0.0002025900\n```\n\n\n:::\n:::\n\n\nFinally we multiply cell probabilities by the value attached to them and sum. This produces four means, one for each group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm <- P %*% sort(y)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]\n[1,]  99.32328\n[2,] 111.21326\n[3,] 121.63880\n[4,] 129.70290\n```\n\n\n:::\n:::\n\n\nWe can also do this with the MASS function `polr()` and car function `Anova()`. The catch is we need to define y as an ordered factor first.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS) # for polr()\nlibrary(car) # for Anova()\ny_ord <- ordered(y)\nf2 <- polr(y_ord ~ group)\ncar::Anova(f2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Deviance Table (Type II tests)\n\nResponse: y_ord\n      LR Chisq Df Pr(>Chisq)    \ngroup   193.31  3  < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\nTo get predicted means we follow the same steps above. The big difference is we need to reverse the sign on the intercepts, which are stored in the \"zeta\" element of the polr object. This is because the `polr()` function models $P(Y \\le y)$. This time let's make a function for this.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmf <- function(model){\n  lp <- c(0, coef(model))\n  intercepts <- model$zeta\n  xb <- sapply(-intercepts, \"+\", lp)\n  P <- matrix(plogis(xb), ncol = length(f2$zeta))\n  P <- cbind(1, P) - cbind(P, 0)\n  m <- P %*% sort(y)\n  m  \n}\n\nmf(f2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          [,1]\n[1,]  99.32265\n[2,] 111.21298\n[3,] 121.63863\n[4,] 129.70252\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}